### ISSUE TITLE
戻ったときにページがの中身が切り替わらない

### ISSUE THREAD

**Issue by t-sakurai816** [yCroma/homebrew-wiki#1]
ページを選択した状態で、ブラウザの戻るボタンを押しても、ページの中身が切り替わりません。
URLは変わっています。

JSの仕様ですか…？

https://user-images.githubusercontent.com/53470730/119914213-ae980800-bf9a-11eb-9708-275f4f5e6c3f.mov

**Comment by yCroma** [comment]
popstateイベントが機能していない感じですね。Issue感謝です。直しておきます。

**Comment by t-sakurai816** [comment]
戻る、進むでも中身が切り替わることを確認しました！
